import type { TSetting } from "src/types";

export const DEFAULT_SETTING: TSetting = {
	versionUpdate: true,
	language: "en",
	dateFormat: "gregorian",
	dailyNoteFormat: "YYYY-MM-DD",
	monthlyNoteNaming: "jalali",
	yearlyNoteNaming: "jalali",
	weekCalculation: "jalali-first-week-start",
	askForCreateNote: true,
	openDailyNoteOnStartup: false,
	showSeasonalNotes: true,
	showHolidays: true,
	weekendDays: "friday",
	hijriBase: "iran",
	showGeorgianDates: true,
	showHijriDates: true,
	dailyNotesPath: "Journal/jYYYY/[Daily]",
	weeklyNotesPath: "Journal/jYYYY/[Weekly]",
	monthlyNotesPath: "Journal/jYYYY/[Monthly]",
	seasonalNotesPath: "Journal/jYYYY/[Seasonal]",
	yearlyNotesPath: "Journal/jYYYY",
	dailyTemplatePath: "",
	weeklyTemplatePath: "",
	monthlyTemplatePath: "",
	seasonalTemplatePath: "",
	yearlyTemplatePath: "",
	showIROfficialEvents: true,
	showIRHistoricalEvents: true,
	showIRAncientEvents: true,
	showGlobalEvents: true,
	showShiaEvents: false,
	showSunniEvents: false,
};
